- name: copy mongodb repo file
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/

- name: install mongodb
  yum:
    name: mongodb-org
    state: installed

- name: update the mongod.conf file to listen for the 0.0.0.0 instead 127.0.0.1
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name:  start the {{ APP }} service and Enable service
  ansible.builtin.systemd:
    name: mongod
    state: restarted
    enabled: yes

- name: download {{ APP }} schema
  include_role:
    name: common
    tasks_from: curl_download
  vars:
    URL: "https://github.com/roboshop-devops-project/mongodb/archive/main.zip"
    EXTRACT_DIR: /tmp/mongodb
    APP_USER: root

- name: load schema
  ansible.builtin.shell: mongo < {{item}}
  loop:
    - catalogue.js
    - users.js
  args:
    chdir: /tmp/mongodb/mongodb-main