- name: Demo on variables in play level
  hosts: all
  vars:
    URL: play.example.com
  tasks:
    - name: print URL
      debug:
        msg: URL = {{ URL }}

- name: Demo on variables in tasks level
  hosts: all
  tasks:
    - name: print URL
      debug:
        msg: URL = {{ URL }}
      vars:
        URL: play.example.com