- name: Demo on variables in play level
  hosts: all
  vars:
    URL: play.example.com
  tasks:
    - name: print URL
      debug:
        msg: URL = {{ URL }}

- name: Demo on variables in tasks level
  hosts: all
  tasks:
    - name: print URL
      debug:
        msg: URL = {{ URL }}
      vars:
        URL: play.example.org

- name: Demo on variables in CLI level
  hosts: all
  tasks:
    - name: print URL1
      debug:
        msg: URL1 = {{ URL1 }}

- name: Demo on variables in files vars
  hosts: all
  vars_files: vars.yml
  tasks:
    - name: print URL2
      debug:
        msg: URL_FILE = {{ URL_FILE }}

- name: Demo on variables in inventory
  hosts: all
  tasks:
    - name: print URL2
      debug:
        msg: URL2 = {{ URL2 }}

- name: Demo on variables in prompt
  hosts: all
  vars_prompt:
    - name: URL3
      prompt: Enter the URL3
      private: no
  tasks:
    - name: print the URL3
      debug:
        msg: URL3 = {{ URL3 }}

# ansible-playbook -i inventory 02-vars.yml -e URL1=play.miak.com  -- command used for this playbook