- name: Demo on runtime variables
  hosts: all
  tasks:
    - name: grab uptime
      shell: uptime
      register: OUT  # out of 2 ways one way is to use register module

    - name: print uptime
      debug:
        msg: "{{ OUT }}"

    - name: print uptime's std out key only
      debug:
        msg: "{{ OUT.stdout }}"

    - name: set a variable
      set_fact: # the second way is to set a variable using the  set_fact module
        UPTIME_OUTPUT: "{{ OUT.stdout }}"

    - name: print uptime
      debug:
        msg: "uptime = {{ UPTIME_OUTPUT }}"