- name: Demo on conditions in anisble
  hosts: all
  tasks:
    - name: Print if Centos
      debug:
        msg: "this shit is centos"
      when: OS == "Redhat"

    - name: Print if Other
      debug:
        msg: "this is not centos"
      when: OS == "windows"