- name: Demo on tags
  hosts: all
  tasks:
    - name: print if centos
      debug:
        msg: "this is centos machine"
      tags:
        - redhat

    - name: print if windows machine
      debug:
        msg: "this is windows machina"
      tags:
        - windows