- name: setup roboshop Project
  hosts: all
  become: yes
  tasks:
    - name: import frontend
      ansible.builtin.import_role:
        name: frontend

    - name: import catalogue
      ansible.builtin.import_role:
        name: catalogue