- name: setup roboshop Project
  hosts: all
  become: yes
  tasks:
    - name: import frontend
      ansible.builtin.import_role:
        name:
      tags: frontend
      #when: APP == "frontend"

    - name: import catalogue
      ansible.builtin.import_role:
        name: catalogue
      tags: catalogue
      #when: APP == "catalogue"