- name: Install Erlang
  ansible.builtin.yum:
    name: https://github.com/rabbitmq/erlang-rpm/releases/download/v23.2.7/erlang-23.2.7-1.el8.x86_64.rpm
    state: present

- name: Setup YUM repos
  shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | sudo bash

- name: Install Rabbitmq Server
  ansible.builtin.yum:
    name: rabbitmq-server
    state: present

- name: Start Rabbitmq Server
  ansible.builtin.systemd:
    name: rabbitmq-server
    state: started
    enabled: yes

- name: Setup RoboShop User
  community.rabbitmq.rabbitmq_user:
    user: roboshop
    password: roboshop123
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present
    tags: administrator