- name: install erlang
  yum:
    name: erlang
    state: present

- name: Upgrade all packages
  yum:
    name: '*'
    state: latest

- name: Setup YUM repositories for RabbitMQ
  shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | sudo bash

- name: install rabbitmq-server
  yum:
    name: rabbitmq-server
    state: present

- name: start rabbitmq server
  systemd:
    name: rabbitmq
    state: started
    enabled: yes

- name: Create application user
  community.rabbitmq.rabbitmq_user:
        user: roboshop
        password: roboshop123
        vhost: /
        configure_priv: .*
        read_priv: .*
        write_priv: .*
        state: present
        tags: administrator