- name: download erlang
  get_url:
    url: https://github.com/rabbitmq/erlang-rpm/releases/download/v23.2.6/erlang-23.2.6-1.el7.x86_64.rpm
    dest: /tmp/{{APP}}

- name: Install erlang
  yum:
    name: /tmp/{{APP}}/erlang-23.2.6-1.el7.x86_64.rpm
    state: present

- name: Setup YUM repositories for RabbitMQ
  shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | sudo bash

- name: install rabbitmq-server
  yum:
    name: rabbitmq-server
    state: latest

- name: start rabbitmq server
  systemd:
    name: rabbitmq
    state: started
    enabled: yes

- name: Create application user
  community.rabbitmq.rabbitmq_user:
        user: roboshop
        password: roboshop123
        vhost: /
        configure_priv: .*
        read_priv: .*
        write_priv: .*
        state: present
        tags: administrator