- name: download {{ APP }} component
  get_url:
    url: "{{URL}}"
    dest: /home/centos/{{APP}}.zip
  become_user: "{{APP_USER}}"

- name: remove old content
  file:
    path: "{{EXTRACT_DIR}}"
    state: absent

- name: create directory for {{ APP }} component
  file:
    path: "{{EXTRACT_DIR}}"
    state: directory
  become_user: "{{APP_USER}}"

- name: Unarchive {{ APP }} component
  ansible.builtin.unarchive:
    src: /home/centos/{{APP}}.zip
    dest: "{{EXTRACT_DIR}}"
    remote_src: yes
  become_user: "{{APP_USER}}"

- name: Rename the Htdocs directory
  shell: mv /usr/share/nginx/html/frontend-main/* /usr/share/nginx/html/
  when: APP == "frontend"

- name: Rename the Htdocs directory
  shell: mv /usr/share/nginx/html/static/* /usr/share/nginx/html/
  when: APP == "frontend"
  #  A shell command is decided to use instead of modules, because ansible is not able to get any module with recursively