- name: download {{ APP }} component
  get_url:
    url: "{{URL}}"
    dest: /home/centos/{{APP}}.zip

- name: remove old content
  file:
    path: "{{EXTRACT_DIR}}"
    state: absent

- name: create directory for {{ APP }} component
  file:
    path: "{{EXTRACT_DIR}}"
    state: directory

- name: Unarchive {{ APP }} component
  ansible.builtin.unarchive:
    src: //home/centos/{{APP}}.zip
    dest: "{{EXTRACT_DIR}}"
    remote_src: yes

- name: Rename the Htdocs directory
  shell: mv /usr/share/nginx/html/static/* /usr/share/nginx/html/.
  when: APP == "frontend"