- name: install maven
  yum:
    name:
      - maven

- name: download {{ APP }} schema
  ansible.builtin.include_tasks: curl_download.yml
  vars:
    EXTRACT_DIR: /home/roboshop/{{APP}}
    APP_USER: roboshop

- name: Install maven Modules
  shell: mvn clean package && mv target/shipping-1.0.jar shipping.jar
  args:
    chdir: /home/roboshop/{{APP}}/{{APP}}-main
  become_user: roboshop

- name: download {{ APP }} schema
  ansible.builtin.include_tasks: systemd.yml
