- name: set the hostname of the {{ APP }} component
  shell: set-hostname {{ APP }}

- name: disable the auto-shutdown for {{ APP }} component
  shell: disable-auto-shutdown

- name: create roboshop user
  ansible.builtin.user:
    name: roboshop
  when: APP == "catalogue" or APP == "user" or APP == "cart" or APP == "shipping" or APP == "payment"