- name: install NodeJS
  yum:
    name:
      - nodejs
      - make
      - gcc-c++

- name: download {{ APP }} schema
  ansible.builtin.include_tasks: curl_download.yml
  vars:
    EXTRACT_DIR: /home/roboshop/{{APP}}
    APP_USER: roboshop

- name: Install NodeJS Modules
  npm:
    path: /home/roboshop/{{APP}}/{{APP}}-main
  become_user: roboshop
#- name: Install NodeJS Modules
#  ansible.builtin.shell:
#    cmd: npm install
#    chdir: /home/roboshop/{{APP}}/{{APP}}-main
#  become_user: roboshop


- name: download {{ APP }} schema
  ansible.builtin.include_tasks: systemd.yml
