- name: install python3
  yum:
    name:
      - python36
      - gcc
      - python3-devel

- name: download {{ APP }} schema
  ansible.builtin.include_tasks: curl_download.yml
  vars:
    EXTRACT_DIR: /home/roboshop/{{APP}}
    APP_USER: roboshop

- name: Install Python Dependencies
  pip:
    requirements: /home/roboshop/{{APP}}/{{APP}}-main/requirements.txt
    executable: pip3

- name: Update User ID in payemnt configuration file
  ansible.builtin.lineinfile:
    path: /home/roboshop/{{APP}}/{{APP}}-main/payment.ini
    regexp: '^uid'
    line: "uid={{RS_UID}}"

- name: Update Group ID in payemnt configuration file
  ansible.builtin.lineinfile:
    path: /home/roboshop/{{APP}}/{{APP}}-main/payment.ini
    regexp: '^gid'
    line: "gid={{RS_UID}}"

#- name: download {{ APP }} schema
#  ansible.builtin.include_tasks: systemd.yml
